### ISSUE TITLE
Provide a development roadmap

### ISSUE THREAD

**Issue by per1234** [codespell-project/actions-codespell#23]
This action has been very useful. Thanks!

The lack of releases may give the impression that it's not ready for production use, but it seems to be pretty good. It would be helpful for interested parties to have some understanding of the development roadmap of this project.

For me, the ideal is to be able to pin the major version ref of an action (e.g., `uses: codespell-project/actions-codespell@v1`) in my workflows, which provides the stability of release versions while also allowing the workflow to benefit from ongoing development work by always using the latest release unless there have been breaking changes (and thus a major version bump).

**Comment by peternewman** [comment]
Hi @per1234 

Yeah I've been a bit lax at doing releases! I've just been using it from master personally in a few places. I didn't realise I'd forgotten to publish it to the Marketplace!

I think there was always something I wanted to add like #19 partly hence not releasing.

Is there anything you want adding, or would doing a v1 release now be sufficient for your usage?

**Comment by per1234** [comment]
We have been using the action in several of Arduino's repositories and community projects that are under very active development and haven't had any problems at all, so I'm pretty happy with it as is.

I am now switching to using the codespell configuration file in all new deployments of the action, so it's possible there will come a time where #19 is wanted, but so far the default location for the file has been acceptable.

If there's anything I might be able to do to help out, please let me know.

**Comment by per1234** [comment]
Congratulations on the 1.0.0 release!

https://github.com/codespell-project/actions-codespell/releases/tag/v1.0

I'm going to close this as resolved by that event. There is one outstanding request:

>to be able to pin the major version ref

However, I think that is best tracked in a dedicated issue, which I have created: https://github.com/codespell-project/actions-codespell/issues/47

Thanks so much for this valuable action, which has become an essential part of the infrastructure of Arduino's GitHub repositories.
