### ISSUE TITLE
Add parameter `uri_ignore_words_list`

### ISSUE THREAD

**Issue by DimitriPapadopoulos** [codespell-project/actions-codespell#36]
Does it make sense? Seems useful to share words between developers running codespell locally and CI.

**Comment by DimitriPapadopoulos** [comment]
`uri_regex` might be useful too, but I would start with `uri_ignore_words_list`.

**Comment by peternewman** [comment]
Feel free to add as few, or as many options as you'd like. Although since the new config file stuff in Codespell, personally I've gone to using that, which takes

> Seems useful to share <EVERYTHING> between developers running codespell locally and CI.

To the next level!

**Comment by DimitriPapadopoulos** [comment]
Oh, I also use config files, `setup.cfg` when it exists, and `.codespellrc` in non-Python projects. For projects with dozens of false positives, a separate file might be interesting.

**Comment by DimitriPapadopoulos** [comment]
I've started working on this see #35. But how could I test?
