### ISSUE TITLE
Not being able to use the projects .codespellrc 

### ISSUE THREAD

**Issue by wb8tyw** [codespell-project/actions-codespell#45]
This is a bug because it doubles the amount of work needed to maintain the codespell settings for a project.

**Comment by per1234** [comment]
Please provide a detailed description of the problem @wb8tyw.

I am successfully using this action in over 100 repositories, configured exclusively via the project's `.codespellrc` file. I have not experienced any problems doing that.

**Comment by wb8tyw** [comment]
It appears after further investigation, I missed committing my .codespellrc file.
I saw the open PR about specifying a config file, and did not verify my configuration first.
