### ISSUE TITLE
expose "dictionary" (--dictionary|-D) option

### ISSUE THREAD

**Issue by yarikoptic** [codespell-project/actions-codespell#62]
ATM not available AFAIK

**Comment by peternewman** [comment]
It is @yarikoptic . See https://github.com/codespell-project/actions-codespell#parameter-builtin

**Comment by yarikoptic** [comment]
it talks about "builtin dictionaries to use.", so I guess `--builtin`, I need `--dictionary` to point to a local custom dictionary file
